import { createSeoMetadata } from "@/app/seo";
import type { Metadata } from "next";
import Link from "@/app/_components/SiteLink";
import MobileNav from "../../_components/MobileNav";
import SolarIcon from "../../_components/SolarIcon";
import registry from "../../docs/generated/theme-registry.json";
import ThemeCommand from "../ThemeCommand";

export const metadata: Metadata = createSeoMetadata({ path: "/themes/editorial-advisor", ...{ title: "Editorial Advisor theme — Coordiation CSS", description: "Preview and install the Editorial Advisor open-code application theme.", openGraph: { title: "Editorial Advisor — Coordiation Themes", description: "A complete editorial consultant portfolio built with Coordiation.", images: ["/themes/editorial-advisor/hero-advisor.png"] }, twitter: { card: "summary_large_image", title: "Editorial Advisor — Coordiation Themes", description: "A complete editorial consultant portfolio built with Coordiation.", images: ["/themes/editorial-advisor/hero-advisor.png"] } } });

export default function EditorialAdvisorThemePage() {
  const theme = registry.themes.find((item) => item.name === "editorial-advisor")!;
  return <main className="theme-detail-page"><header className="site-header"><Link className="brand" href="/" aria-label="Coordiation CSS home"><img src="/coordiation-logo.png" alt="" /><span>Coordiation</span><span className="brand-product">Themes</span></Link><nav aria-label="Main navigation"><Link href="/themes">All themes</Link><Link href="/components">Components</Link><Link href="/icons">Icons</Link><Link href="/docs/themes">Docs</Link></nav><MobileNav /><Link className="header-cta" href={theme.preview}>Full preview <SolarIcon name="arrow-to-top-right" size={15} /></Link></header>
    <section className="theme-detail-hero"><div><p className="component-overline">THEME 001 · {theme.status.toUpperCase()}</p><h1>{theme.title}</h1><p>{theme.description} Inspired by classic editorial composition and rebuilt as an original, responsive Coordiation application.</p><div className="theme-tags">{theme.categories.map((category)=><span key={category}>{category}</span>)}</div></div><div><ThemeCommand command={theme.command} /><small>The Coordiation CLI installs the editable page, stylesheet, icon component, required SVG files, and all three original media assets.</small></div></section>
    <section className="theme-preview-frame"><div className="theme-browser-bar"><span><i/><i/><i/></span><code>/editorial-advisor</code><Link href={theme.preview}>Open full screen <SolarIcon name="arrow-to-top-right" size={14}/></Link></div><iframe src={theme.preview} title="Editorial Advisor live theme preview" loading="eager" /></section>
    <section className="theme-detail-spec"><div><p className="component-overline">STRUCTURE</p><h2>{theme.sections.length} purposeful sections</h2><p>Each section has a stable semantic identity so a person or AI agent can safely remove, reorder, rewrite, or extend it.</p></div><ol>{theme.sections.map((section,index)=><li key={section}><span>{String(index+1).padStart(2,"0")}</span><b>{section}</b></li>)}</ol></section>
    <section className="theme-detail-files"><div><p className="component-overline">OWN THE SOURCE</p><h2>Coordiation source.<br />Original assets.</h2></div><div><h3>Installed files</h3>{theme.files.map(file=><code key={file.target}>{file.target}</code>)}<h3>Public assets</h3>{theme.assets.map(asset=><code key={asset}>{asset}</code>)}</div><aside><SolarIcon name="code" size={26}/><p>Reusable layout primitives use literal <code>co-*</code> utilities. Only the theme-specific editorial composition remains under the <code>ea-*</code> namespace.</p><a href={theme.installPath}>Inspect registry item <SolarIcon name="arrow-to-top-right" size={14} /></a></aside></section>
    <section className="theme-detail-cta"><p className="component-overline">READY TO ADAPT</p><h2>Make the story yours.</h2><p>Replace the identity, copy, contact details, and images while preserving the accessible hierarchy and responsive structure.</p><ThemeCommand command={theme.command} /></section>
  </main>;
}
