export type CapabilityStatus = "complete" | "partial" | "planned";

export type Capability = {
  id: string;
  area: string;
  status: CapabilityStatus;
  target: string;
  examples: string[];
  note: string;
};

export const capabilities: Capability[] = [
  { id: "source-detection", area: "Plain-text source detection", status: "complete", target: "0.1", examples: ["class=\"co-flex\""], note: "Static candidates are extracted without evaluating templates." },
  { id: "framework-scanning", area: "Framework source scanning", status: "complete", target: "0.1", examples: [".coord", ".tsx", ".vue", ".svelte"], note: "Coord, HTML, JSX/TSX, Vue, Svelte, Astro, and Markdown are covered." },
  { id: "static-output", area: "Static CSS / zero runtime", status: "complete", target: "0.1", examples: ["@coordiation;"], note: "Compilation emits layered CSS and no browser JavaScript." },
  { id: "theme-variables", area: "CSS-first theme variables", status: "complete", target: "0.1", examples: ["--co-color-brand-500", "--co-perspective-product", "--co-animate-wiggle"], note: "Colors, backgrounds, spacing, fonts, radii, shadows, filters, perspective, transition easing/defaults, animations, and breakpoints are tokenized." },
  { id: "custom-prefix", area: "Custom utility prefix", status: "complete", target: "0.1", examples: ["co-flex"], note: "The compiler prefix is configurable." },
  { id: "important", area: "Important utilities", status: "complete", target: "0.1", examples: ["!co-hidden"], note: "Leading and trailing important modifiers are supported." },
  { id: "arbitrary", area: "Arbitrary properties and values", status: "complete", target: "0.2", examples: ["co-text-[length:2rem]", "co-bg-[image:linear-gradient(to_right,#000,#fff)]", "co-[mask-type:luminance]"], note: "Typed ambiguity resolution, escaped underscores, declaration validation, and contextual value inference are implemented and tested." },
  { id: "responsive", area: "Responsive breakpoints", status: "complete", target: "0.1", examples: ["md:co-grid-cols-3"], note: "Named min/max and arbitrary breakpoints compile." },
  { id: "state-variants", area: "State and structural variants", status: "complete", target: "0.2", examples: ["hover:co-bg-black", "nth-[2n+1_of_li]:co-block", "user-invalid:co-border-black", "before:co-block"], note: "Interactive, form, structural, nth, child, open/inert, and pseudo-element variants are registry-backed and exhaustively tested." },
  { id: "context-variants", area: "Dark, RTL, group, and peer", status: "complete", target: "0.2", examples: ["dark:co-text-white", "group-hover/card:co-block", "peer-invalid:co-visible", "in-focus:co-opacity-100"], note: "Dark and bidirectional contexts plus every-state, named, arbitrary, has, nested, and implicit group/peer relationships are registry-backed and tested." },
  { id: "attribute-variants", area: "ARIA, data, has, and not", status: "complete", target: "0.2", examples: ["aria-expanded:co-block", "data-[state=open]:co-block", "has-checked:co-ring-2", "not-focus:co-opacity-50"], note: "Boolean and arbitrary attributes, group/peer composition, has/not conditions, and arbitrary selectors are registry-backed, documented, validated, and tested." },
  { id: "conditional-variants", area: "Media, supports, and container variants", status: "complete", target: "0.2", examples: ["motion-safe:co-transition", "not-supports-[display:grid]:co-block", "@md/sidebar:co-grid-cols-2", "[@media(pointer:fine)]:co-block"], note: "Registered media conditions, feature queries, starting styles, named and arbitrary container queries, and safe arbitrary conditional at-rules are documented and tested." },
  { id: "preflight", area: "Preflight / normalized base", status: "complete", target: "0.2", examples: ["@layer co-base", "preflight: false", "--no-preflight"], note: "A registry-backed cross-browser reset covers box sizing, typography, lists, media, forms, date/time controls, placeholders, and hidden-until-found; it is documented, tested, extensible, and optional." },
  { id: "layout", area: "Layout and positioning", status: "complete", target: "0.2", examples: ["co-aspect-3/2", "co-sticky", "-co-inset-x-4", "co-inset-bs-4", "co-break-inside-avoid", "-co-z-10", "co-object-[25%_75%]"], note: "Display, box model, aspect ratio, page/column breaks, position and physical/logical inset—including inline and block edges—float/clear, isolation, overflow/overscroll, object fit/position, visibility, and z-index are registry-backed, documented, and tested." },
  { id: "flex-grid", area: "Flexbox and grid", status: "complete", target: "0.2", examples: ["co-flex-[3_1_auto]", "co-grow-3", "co-basis-sm", "co-items-center-safe", "co-grid-cols-subgrid", "-co-col-start-2"], note: "Flex shorthand, direction, wrapping, grow/shrink/basis/order, safe alignment, explicit and implicit grid tracks, subgrid, flow, complete row/column placement, theme tokens, custom properties, arbitrary values, and negative lines are documented and tested." },
  { id: "spacing-sizing", area: "Spacing and sizing", status: "complete", target: "0.2", examples: ["co-pbs-4", "-co-mbe-2", "co-space-x-reverse", "co-scroll-pbe-(--offset)", "co-w-md", "co-h-dvh", "co-max-inline-lg", "co-min-block-24"], note: "Physical and logical padding/margin, gaps, reversible sibling spacing, every scroll edge, inset aliases, physical/logical dimensions, min/max constraints, container tokens, fractions, intrinsic/viewport values, custom properties, arbitrary values, and negative-value boundaries are registry-backed, documented, and tested." },
  { id: "typography", area: "Typography", status: "complete", target: "0.2", examples: ["co-text-sm/6", "co-font-stretch-condensed", "co-font-features-(--features)", "co-tabular-nums", "co-list-image-none", "co-wrap-anywhere", "-co-tracking-wide", "before:co-content-['AI_ready']"], note: "Font families and metadata, type scale and line-height modifiers, smoothing/style/weight/stretch, numeric variants, OpenType features, tracking, clamp, lists, alignment, colors, decoration, transforms, overflow and wrapping, indentation, tabs, vertical alignment, whitespace, word breaking, hyphenation, and generated content are registry-backed, documented, and tested." },
  { id: "backgrounds", area: "Backgrounds, gradients, and colors", status: "complete", target: "0.3", examples: ["co-bg-black/50", "co-bg-[url(/hero.svg)]", "co-bg-linear-to-r/oklch", "co-from-brand-500", "co-via-40%", "co-to-transparent", "co-bg-position-(--focus)", "co-bg-size-[auto_12rem]"], note: "Colors, images, attachment, clip, origin, position, repeat, size, linear/radial/conic gradients, composable color stops and positions, interpolation modes, theme image tokens, custom properties, and safe arbitrary values are registry-backed, documented, and tested." },
  { id: "borders", area: "Border, outline, ring, and divide", status: "complete", target: "0.3", examples: ["co-border-bs-2", "co-border-e-brand-500/50", "co-rounded-se-(--radius)", "focus:co-outline-2", "-co-outline-offset-2", "co-ring-2", "co-inset-ring-brand-500", "co-divide-x-reverse", "co-divide-dashed"], note: "Physical and logical widths and colors, styles, complete radius placement, outline width/color/style/offset, composable outward and inset rings, compatibility ring offsets, and divider width/reversal/color/style are registry-backed, documented, and tested." },
  { id: "effects", area: "Effects, filters, backdrop filters, and masks", status: "complete", target: "0.3", examples: ["co-shadow-lg", "co-text-shadow-sm", "co-opacity-50", "co-mix-blend-multiply", "co-blur-md", "co-backdrop-blur-sm", "co-mask-[url(/mask.svg)]"], note: "Composable box/inset/text shadows and colors, opacity, standard blend modes, filter and backdrop-filter functions, direct filter escape hatches, mask images and geometry, SVG mask modes, CSS-first tokens, arbitrary values, and negative hue or mask angles are registry-backed, documented, and tested." },
  { id: "tables-columns", area: "Tables and multi-column", status: "complete", target: "0.3", examples: ["co-table-fixed", "co-border-separate", "co-border-spacing-x-3", "co-caption-bottom", "co-columns-sm", "co-column-span-all", "co-column-rule-brand-500"], note: "Semantic table display roles, automatic/fixed layout, collapse, independent border spacing, captions, multi-column counts and ideal-width tokens, gaps and breaks, fill, spanning, column-rule width/color/style, CSS-first tokens, custom properties, and safe arbitrary values are registry-backed, documented, and tested." },
  { id: "transforms", area: "Transforms and perspective", status: "complete", target: "0.3", examples: ["-co-translate-x-4", "co-translate-z-8", "co-rotate-y-45", "co-transform-3d", "co-perspective-normal", "co-backface-hidden", "co-zoom-110"], note: "Composable 2D/3D translate and rotate, scale and skew axes, origins, transform resets and CPU/GPU modes, flat/preserved scenes, CSS-first perspective and origins, backface visibility, zoom, custom properties, arbitrary values, and negative-value boundaries are registry-backed, documented, and tested." },
  { id: "transitions", area: "Transitions and animations", status: "complete", target: "0.3", examples: ["co-transition", "co-transition-discrete", "co-duration-300", "co-ease-out", "co-animate-spin", "motion-reduce:co-animate-none", "starting:co-opacity-0"], note: "Named and arbitrary transition properties, discrete behavior, CSS-first defaults, duration, delay, easing, starting styles, reduced-motion variants, namespaced spin/ping/pulse/bounce keyframes, custom animations, registry metadata, and unsafe-value rejection are implemented, documented, and tested." },
  { id: "svg", area: "SVG fill and stroke", status: "complete", target: "0.2", examples: ["co-fill-current", "co-stroke-black", "co-stroke-2"], note: "Theme/arbitrary fill and stroke colors plus token and arbitrary stroke widths are implemented and tested." },
  { id: "icons", area: "Solar Linear and Iconsax Line Oval libraries", status: "complete", target: "1.0", examples: ["@coordiation/icons/linear/home", "@coordiation/icons/iconsax-line-oval/airdrop", "renderIcon()", "/icon-registry.json"], note: "All 2,165 icons across Solar Linear (1,246) and Iconsax Line Oval (919) ship through collection-safe literal subpaths with accessible rendering helpers, local assets, CSS variables, an AI-readable registry, pinned upstream provenance, and per-collection license metadata." },
  { id: "component-registry", area: "Open-code component registry", status: "complete", target: "1.0", examples: ["/components", "/r/button.json", "/component-registry.json", "@/components/ui/button"], note: "All 64 components have independent Coordiation implementations shipped as owned source through first-party catalog and item endpoints, with literal co-* utilities, previews, client-boundary metadata, usage examples, and AI-readable accessibility contracts." },
  { id: "registry-cli", area: "First-party source installer", status: "complete", target: "1.0", examples: ["npx @coordiation/cli@latest add component button", "npx @coordiation/cli@latest add theme editorial-advisor", "--dry-run", "--force"], note: "The official @coordiation/cli installs component and theme source from the Coordiation registry, validates names and project-scoped targets, downloads declared theme assets, writes atomically, skips identical files, and refuses changed-file overwrites unless explicitly forced." },
  { id: "agent-context", area: "Compact AI agent context", status: "partial", target: "0.2", examples: ["coordiation inspect --write", "coordiation context pricing", ".coordiation/agent-manifest.json", "@coordiation/agent"], note: "The deterministic project inspector, versioned manifest schema, seven task context packs, literal-utility summaries, project contracts, warnings, and compact/full output modes are implemented and tested. The remaining release gate is publishing @coordiation/agent together with the updated CLI, followed by measured agent evaluations across supported frameworks." },
  { id: "themes", area: "Installable application themes", status: "complete", target: "1.0", examples: ["/themes/editorial-advisor", "/themes/quiet-journal", "/themes/finance-dashboard", "/themes/industrial-forge", "/themes/mono-portfolio", "/theme-registry.json"], note: "Editorial Advisor, Quiet Journal, Finance Dashboard, Industrial Forge, and Mono Portfolio ship as complete responsive Next.js applications with live previews, verified co-* utility foundations, bundled Coordiation icons and UI primitives, namespaced design tokens, optional original media, first-party CLI items, Coordiation copyright, and AI-readable customization contracts." },
  { id: "accessibility", area: "Accessibility and forced colors", status: "complete", target: "0.2", examples: ["co-sr-only", "co-forced-color-adjust-none", "co-scheme-light-dark"], note: "Screen-reader visibility, forced-color adjustment, color schemes, and forced-color variants are implemented and tested." },
  { id: "interaction", area: "Interactivity utilities", status: "complete", target: "0.3", examples: ["co-cursor-(--control-cursor)", "co-field-sizing-content", "co-scrollbar-thumb-brand-500", "co-scrollbar-gutter-stable", "co-snap-always", "co-touch-pan-y", "co-touch-pinch-zoom", "co-will-change-[contents,transform]"], note: "Every standard cursor keyword, field sizing, pointer and selection controls, resize, scroll behavior, composable scrollbar colors, width and gutter, complete snap behavior, composable touch gestures, custom properties, arbitrary values, and unsafe-value rejection are documented and tested." },
  { id: "logical", area: "Logical properties and writing modes", status: "complete", target: "0.3", examples: ["co-direction-rtl", "co-writing-vertical-rl", "co-text-orientation-upright", "co-unicode-bidi-isolate", "co-text-combine-digits-2", "co-mbs-4", "co-inset-be-2", "co-max-inline-lg", "co-border-s-2"], note: "Direction, all horizontal/vertical/sideways writing modes, glyph orientation, Unicode bidi controls, upright composition, logical spacing/inset/sizing/borders/radii/scrolling, context variants, semantic guidance, and progressive-enhancement boundaries are documented and tested." },
  { id: "modern-color", area: "Modern color and color mixing", status: "complete", target: "0.3", examples: ["--co-color-signal--p3", "co-bg-signal/80", "co-bg-[color:color(display-p3_1_0_0)]", "co-bg-linear-to-r/display-p3", "co-bg-conic/decreasing"], note: "OKLab/OKLCH, Lab/LCH, typed Color Level 4 values, OKLab opacity mixing, eight gradient interpolation spaces, hue-path controls, and paired Display-P3 tokens with automatic syntax, output-gamut, and fallback guards are documented and tested." },
  { id: "custom-utility", area: "Custom utility registration", status: "complete", target: "0.4", examples: ["@co-utility content-auto", "@co-utility tab-*", "co-value()", "co-modifier()"], note: "CSS-first static and functional patterns cover theme, bare, arbitrary, default, modifier, ratio, explicit negative, variant, important, validation, override, and machine-readable manifest behavior." },
  { id: "custom-variant", area: "Custom variant registration", status: "complete", target: "0.4", examples: ["@co-variant theme-midnight (&:where([data-theme=midnight] *))", "@co-variant grid-ready (@supports (display: grid))", "@co-slot"], note: "CSS-first selector, media/supports/container, and compound wrapper variants stack with built-ins, support deliberate overrides, fail fast on malformed definitions, and publish a machine-readable compile manifest." },
  { id: "plugin-api", area: "Plugin API", status: "complete", target: "0.4", examples: ["defineCoordiationPlugin()", "addUtilities()", "addVariant()", "extendTheme()", "addExtractor()", "addSafelist()"], note: "Synchronous reusable plugins register validated utilities, variants, theme extensions, source extractors, and safelists across the compiler, Vite, and PostCSS with deterministic precedence and a serializable AI manifest." },
  { id: "sources", area: "Source include, exclude, and safelist", status: "complete", target: "0.2", examples: ["include: []", "exclude: []", "safelist: []"], note: "Glob filters, explicit candidates, CLI flags, validation, and dynamic-class diagnostics are implemented and tested." },
  { id: "extraction-hooks", area: "Framework extraction hooks", status: "complete", target: "0.2", examples: ["extractors: { '.coord': extract }"], note: "Extension and global extraction hooks supplement plain-text scanning and validate every returned candidate." },
  { id: "vite", area: "Vite adapter", status: "complete", target: "0.2", examples: ["coordiation({ content: ['src'], cssFile: 'src/coordiation.css' })", "virtual:coordiation.css"], note: "Root-aware scanning, watched CSS input, virtual stylesheet generation, precise template/theme invalidation, add/delete rescans, CSS HMR module propagation, safe full-reload fallback, diagnostics, and source dependency registration are documented and tested." },
  { id: "postcss", area: "PostCSS adapter", status: "complete", target: "0.2", examples: ["coordiation({ content: ['src'], cwd: process.cwd() })", "@coordiation;"], note: "PostCSS 8 plugin metadata, marker-scoped multi-entry safety, asynchronous transformation, authored-CSS and source-map compatibility, downstream plugin ordering, root-aware scanning, file and directory dependency messages, standard warnings, package metadata, changelog, documentation, and a real pipeline fixture are complete." },
  { id: "cli", area: "CLI and watch mode", status: "complete", target: "0.2", examples: ["coordiation-css --content src --watch", "--poll 500"], note: "One-shot builds plus portable input/source polling, edit/create/delete detection, serialized atomic output, recoverable errors, configurable intervals, and graceful signal shutdown are documented and process-tested." },
  { id: "css-toolchain", area: "Bundling, nesting, prefixing, minification", status: "complete", target: "0.5", examples: ["@import", "compileWithToolchain()", "toolchain: { minify: true }", "--target safari=15.4"], note: "Lightning CSS bundles local imports before compilation, then lowers nesting, applies explicit target-aware prefixes, and optionally minifies; imported files are tracked by Vite, PostCSS, CLI watch mode, and the AI-readable toolchain manifest." },
  { id: "cache", area: "Incremental build cache", status: "complete", target: "0.5", examples: ["createIncrementalBuildCache()", ".coordiation-cache", "--no-cache"], note: "File-level candidate and diagnostic reuse, compilation reuse, imported-CSS validation, add/edit/delete invalidation, atomic CLI persistence, process-local adapter caches, and AI-readable hit/miss manifests are implemented and tested." },
  { id: "source-maps", area: "Source maps", status: "complete", target: "0.5", examples: ["sourceMap: true", "app.css.map", "--sourcemap-inline"], note: "Source Map v3 output preserves entry and imported CSS identities through framework generation, nesting, prefixing, and minification, with native Vite/PostCSS delivery plus external or inline CLI output." },
  { id: "language-server", area: "IntelliSense / language server", status: "complete", target: "0.6", examples: ["coordiation-language-server --stdio", "textDocument/completion", "coordiation/inspectCandidate"], note: "The editor-agnostic LSP 3.17 server provides registry-backed completion, compiler-authored hover CSS, unsupported/deprecated/dynamic diagnostics, CSS-first project configuration, and AI-readable manifest/inspection requests." },
  { id: "formatter", area: "Class sorting formatter", status: "complete", target: "0.6", examples: ["coordiation-format --check", "coordiation-format --write", "formatterManifest"], note: "The formatter delegates utility ordering to the canonical compiler comparator, keeps application classes stable, preserves dynamic expressions, and provides programmatic edit data plus check, write, stdin, and JSON CLI modes." },
  { id: "codemods", area: "Upgrade and codemod tools", status: "complete", target: "0.9", examples: ["coordiation-upgrade --check", "coordiation-upgrade --write", "upgradeManifest"], note: "Versioned safe transforms consume the compiler deprecation registry, migrate legacy negative syntax with variants and custom prefixes, preserve dynamic source, and expose exact multi-file JSON plans." },
  { id: "native-scanner", area: "Cross-platform native scanner", status: "complete", target: "1.0", examples: ["scanSourcesNative()", "engine: 'native'", "fallback: false"], note: "The optional dependency-free C11 engine batches literal candidate extraction across Linux, macOS, and Windows targets; its wrapper preserves filters, safelists, diagnostics, custom-prefix validation, explicit engine metadata, and a JavaScript fallback." },
  { id: "compatibility", area: "Compatibility and deprecation policy", status: "complete", target: "1.0", examples: ["createCompatibilityManifest()", "deprecationRegistry", "result.deprecations"], note: "A versioned semantic-versioning policy defines stable surfaces, prerelease behavior, deprecation windows, earliest removal, compiler diagnostics, machine-readable replacements, and mandatory codemod ownership." },
];

export const capabilityManifest = {
  schemaVersion: "1.0",
  framework: "Coordiation CSS",
  version: "0.2-dev",
  generatedAt: "2026-08-31",
  prefix: "co-",
  negativeSyntax: "-co-{utility}",
  statuses: {
    complete: "Documented, tested, and available",
    partial: "Usable subset available; see note for remaining work",
    planned: "Not shipped yet",
  },
  capabilities,
};
