import type { Metadata } from "next";
import ThemeIcon from "./ThemeIcon";
import { PlanCard, PortfolioButton, SectionTag, ServiceCell } from "./DashboardComponents";
import "./mono-portfolio.css";

export const metadata: Metadata = { title: "Mono Portfolio — Mika Arden", description: "An original creative designer portfolio template built with Coordiation." };

const tools = [
  ["widget-4", "Figma", "Interface systems and rapid collaborative prototyping."],
  ["palette", "Webflow", "Expressive editorial websites with dependable structure."],
  ["code", "Code", "Production-minded components and accessible interactions."],
  ["monitor", "Framer", "High-fidelity motion studies and launch-ready pages."],
] as const;

const projects = ["Orbit Finance System", "Sonder Travel Platform", "Kindred Health Service", "Morrow Culture Journal"];

const faqs = [
  ["What happens in the first week?", "We align on audience, business goals, constraints, success signals, and the smallest useful release."],
  ["Can you work with our existing brand?", "Yes. I can extend a mature system or clarify an identity that has grown inconsistent."],
  ["Do you collaborate with developers?", "Always. Design decisions are documented for implementation and reviewed with the people building them."],
  ["Can the scope grow after launch?", "Yes. The system is intentionally structured so new pages and flows can be added without starting over."],
];

const posts = [
  ["blog-team.jpg", "May 29, 2026", "Designing through disagreement without losing momentum"],
  ["blog-design.jpg", "May 21, 2026", "The quiet details that make an interface feel trustworthy"],
  ["blog-wireframe.jpg", "May 12, 2026", "Why clear wireframes lead to braver visual systems"],
];

export default function MonoPortfolioPreview() {
  return <main className="mono-portfolio co-overflow-hidden" id="top">
    <header className="mp-header co-grid co-items-center"><a className="mp-brand co-flex co-items-center" href="#top"><b>M.</b><span>Mika Arden<br /><small>Designer &amp; creative developer</small></span></a><nav className="co-flex co-items-center co-justify-center" aria-label="Portfolio navigation"><a href="#about">About</a><a href="#work">Work</a><a href="#services">Services</a><a href="#pricing">Pricing</a><a href="#contact">Contact</a></nav><a className="mp-header-cta co-flex co-items-center co-justify-between" href="#contact">Let&apos;s talk <ThemeIcon name="arrow-to-top-right" size={18} tone="light" /></a><details className="mp-menu"><summary aria-label="Open navigation"><ThemeIcon name="hamburger-menu" size={22} /></summary><div><a href="#about">About</a><a href="#work">Work</a><a href="#services">Services</a><a href="#pricing">Pricing</a><a href="#contact">Contact</a></div></details></header>

    <section className="mp-hero co-grid co-items-center"><div className="mp-hero-copy"><SectionTag>Available for select projects</SectionTag><h1>Useful brands.<br />Clear digital<br /><em>experiences.</em></h1><p>Strategy, identity, and interface design for teams creating products people can understand, trust, and keep using.</p><div className="mp-actions co-flex co-items-center"><PortfolioButton href="#work">View work</PortfolioButton><a href="#contact">Contact me <ThemeIcon name="arrow-to-top-right" size={14} /></a></div></div><div className="mp-hero-board co-grid"><figure className="co-relative co-overflow-hidden"><img className="co-w-full co-h-full co-object-cover" src="/themes/mono-portfolio/hero.jpg" alt="Portrait of Mika Arden, independent designer" /></figure><aside className="mp-location"><ThemeIcon name="map-point" size={17} /><b>Jakarta, Indonesia</b><small>Working worldwide</small></aside><aside className="mp-social"><small>Find me</small><div className="co-flex"><a href="#contact">IG</a><a href="#contact">IN</a><a href="#contact">BE</a></div></aside><aside className="mp-count"><strong>180+</strong><span>Projects shaped</span><small><ThemeIcon name="star" size={13} /> 4.9 average partner rating</small></aside><aside className="mp-skills co-flex co-items-center"><b>Specializing in</b><span>UX/UI</span><span>Brand systems</span><span>Frontend</span></aside></div></section>

    <section className="mp-marquee" aria-label="Services"><div className="co-flex co-items-center co-animate-[mp-marquee_24s_linear_infinite] motion-reduce:co-animate-none">{[0,1].map(set=><span className="co-flex co-items-center" key={set}>UI/UX Design <i/> Web Design <i/> Brand Systems <i/> Frontend <i/> Creative Direction <i/></span>)}</div></section>

    <section className="mp-section mp-about co-grid" id="about"><div className="mp-about-copy"><SectionTag>About me</SectionTag><h2>Curiosity into<br />clear, useful<br />outcomes.</h2><p>I&apos;m Mika, an independent designer who helps growing teams turn complicated ideas into focused identities and digital products. My work lives between structure and personality.</p><PortfolioButton href="#services">Learn more</PortfolioButton></div><figure className="co-relative co-overflow-hidden"><img className="co-w-full co-h-full co-object-cover" src="/themes/mono-portfolio/about.jpg" alt="Mika Arden in a studio portrait" /></figure><div className="mp-tools"><b>Tools and practices</b>{tools.map(([icon,title,copy])=><article className="co-grid co-items-center" key={title}><ThemeIcon name={icon} size={23} /><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>

    <section className="mp-section mp-work" id="work"><div className="mp-heading co-flex co-items-end co-justify-between"><div><SectionTag>Selected work</SectionTag><h2>Projects with a<br />point of view.</h2></div><p>From digital services to editorial products, every engagement starts with what people need to understand and do.</p></div><div className="mp-work-grid co-grid"><a className="mp-feature-project co-relative co-overflow-hidden" href="#contact"><img className="co-w-full co-h-full co-object-cover co-transition co-duration-300 co-ease-out" src="/themes/mono-portfolio/project.jpg" alt="Laptop presenting a financial product interface" /><div className="co-absolute"><small>2026 · UX/UI · Design system</small><h3>Orbit Finance Control Room</h3><ThemeIcon name="arrow-to-top-right" size={18} tone="light" /></div></a><div className="mp-project-list">{projects.map((project,index)=><a className="co-flex co-items-center co-justify-between" href="#contact" key={project}><span>{project}</span><small>0{index+1}</small></a>)}<PortfolioButton href="#contact">View more</PortfolioButton></div></div></section>

    <section className="mp-section mp-services" id="services"><div className="mp-heading is-centered co-text-center"><SectionTag centered>Services</SectionTag><h2>Services for<br />modern brands.</h2><p>Choose a focused engagement or combine capabilities around the exact outcome your team needs.</p></div><div className="mp-service-grid co-grid"><ServiceCell number="01" icon="widget-4" title="UX/UI design" copy="Clear product flows, systems, and interfaces that make complex work feel manageable." /><ServiceCell number="02" icon="monitor" title="Web design" copy="Editorial websites with strong hierarchy, deliberate rhythm, and responsive detail." /><ServiceCell number="03" icon="pen-new-square" title="Brand systems" copy="Identity foundations that give every channel a shared, recognizable voice." /><ServiceCell number="04" icon="code" title="Frontend systems" copy="Accessible component thinking that bridges design intent and production reality." /><ServiceCell number="05" icon="lightbulb" title="Creative strategy" copy="Positioning, principles, and priorities that make the next decisions easier." /><ServiceCell number="06" icon="palette" title="Art direction" copy="A coherent image, typography, and motion language for a memorable launch." /></div></section>

    <section className="mp-trust co-grid"><div><SectionTag>Why choose Mono</SectionTag><h2>Clarity.<br />Character.<br />Momentum.</h2></div><div className="mp-trust-points co-grid"><article><span>01</span><ThemeIcon name="widget-4" size={20} tone="lime" /><h3>Modern, minimal systems</h3><p>Enough structure to scale without flattening the brand.</p></article><article><span>02</span><ThemeIcon name="lightbulb" size={20} tone="lime" /><h3>Strategy-led creativity</h3><p>Every expressive choice has a reason and a job to do.</p></article><figure className="co-overflow-hidden"><img className="co-w-full co-h-full co-object-cover" src="/themes/mono-portfolio/workspace.jpg" alt="A bright creative studio workspace" /></figure><article><span>03</span><ThemeIcon name="users-group-rounded" size={20} tone="lime" /><h3>Responsive collaboration</h3><p>Short feedback loops keep the work moving and visible.</p></article><article><span>04</span><ThemeIcon name="eye" size={20} tone="lime" /><h3>Attention to detail</h3><p>The final ten percent receives the same care as the first idea.</p></article></div></section>

    <section className="mp-section mp-pricing" id="pricing"><div className="mp-heading is-centered co-text-center"><SectionTag centered>Pricing</SectionTag><h2>A plan for your<br />next goal.</h2><p>Transparent starting points that can be adjusted around scope, timing, and team.</p></div><div className="mp-plan-grid co-grid"><PlanCard name="Starter" price="$2.4k" /><PlanCard name="Professional" price="$5.8k" featured /><PlanCard name="Partnership" price="$9.6k" /></div></section>

    <section className="mp-section mp-reviews"><div className="mp-heading co-flex co-items-end co-justify-between"><div><SectionTag>Reviews</SectionTag><h2>Good work,<br />built together.</h2></div><p>Direct communication, honest critique, and steady progress from the first conversation to launch.</p></div><div className="mp-review-grid co-grid"><aside><strong>4.9<small>/5</small></strong><p>Rated by partners across product, culture, and public-service teams.</p><div>★★★★★</div><PortfolioButton href="#contact">Start a project</PortfolioButton></aside><blockquote><span>“</span><p>Mika brought rigor without making the process rigid. The new system finally sounds and works like us.</p><footer><b>Rania Prasetyo</b><small>Product Director, Morrow</small></footer></blockquote><figure className="co-overflow-hidden"><img className="co-w-full co-h-full co-object-cover" src="/themes/mono-portfolio/reviewer.jpg" alt="Rania Prasetyo, product director" /></figure><div className="mp-review-notes"><article><ThemeIcon name="heart" size={16} /><p>Every workshop gave our team a decision we could immediately use.</p><small>Aji · Kindred</small></article><article><ThemeIcon name="heart" size={16} /><p>The interface feels distinct without asking users to relearn familiar patterns.</p><small>Nadia · Orbit</small></article></div></div></section>

    <section className="mp-section mp-faq co-grid"><div><SectionTag>FAQ</SectionTag><h2>Before<br />we begin.</h2><p>A useful partnership starts with shared expectations. Here are the answers teams usually need first.</p><PortfolioButton href="#contact">Ask another question</PortfolioButton></div><div>{faqs.map(([question,answer],index)=><details key={question} open={index===0}><summary className="co-flex co-items-center co-justify-between">{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>

    <section className="mp-section mp-journal"><div className="mp-heading is-centered co-text-center"><SectionTag centered>Journal</SectionTag><h2>Ideas worth<br />sharing.</h2><p>Notes on product thinking, useful brands, collaboration, and designing work that lasts.</p></div><div className="mp-post-grid co-grid">{posts.map(([image,date,title])=><article className="co-transition co-duration-300 co-ease-out" key={title}><img className="co-w-full co-object-cover" src={`/themes/mono-portfolio/${image}`} alt="" /><div><small><ThemeIcon name="calendar" size={13} tone="lime" />{date}</small><h3>{title}</h3><a className="co-inline-flex co-items-center" href="#contact">Read note <ThemeIcon name="arrow-right" size={14} tone="lime" /></a></div></article>)}</div></section>

    <footer className="mp-footer" id="contact"><div className="mp-footer-cta co-flex co-items-center co-justify-between"><h2>Let&apos;s make<br />something useful.</h2><PortfolioButton href="mailto:hello@mono.example" light>Start a project</PortfolioButton></div><div className="mp-footer-main co-grid"><a className="mp-brand co-flex co-items-center" href="#top"><b>M.</b><span>Mono Portfolio<br /><small>Independent creative practice</small></span></a><div><b>Menu</b><a href="#about">About</a><a href="#work">Work</a><a href="#services">Services</a></div><div><b>Contact</b><a href="mailto:hello@mono.example">hello@mono.example</a><a href="#contact">Jakarta · worldwide</a><a href="#contact">+62 812 9000 1820</a></div><div><b>Elsewhere</b><a href="#contact">Instagram</a><a href="#contact">LinkedIn</a><a href="#contact">Behance</a></div></div><div className="mp-footer-bottom co-flex co-items-center co-justify-between"><span>© 2026 Coordiation. All rights reserved.</span><a className="co-inline-flex co-items-center" href="#top">Back to top <ThemeIcon name="arrow-to-top-right" size={14} tone="light" /></a></div></footer>
  </main>;
}
