import { createSeoMetadata } from "@/app/seo";
import type { Metadata } from "next";
import Link from "@/app/_components/SiteLink";
import MobileNav from "../../_components/MobileNav";
import SolarIcon from "../../_components/SolarIcon";
import registry from "../../docs/generated/theme-registry.json";
import ThemeCommand from "../ThemeCommand";

export const metadata: Metadata = createSeoMetadata({ path: "/themes/studio-index", title: "Studio Index theme — Coordiation CSS", description: "Preview and install the Studio Index open-code brand and product designer portfolio theme.", openGraph: { title: "Studio Index — Coordiation Themes", description: "A minimal portfolio and case-study system built with Coordiation components and CSS utilities.", images: ["/themes/studio-index/root-table.jpg"] }, twitter: { card: "summary_large_image", title: "Studio Index — Coordiation Themes", description: "A minimal designer portfolio with expandable case studies.", images: ["/themes/studio-index/root-table.jpg"] } });

export default function StudioIndexThemePage() {
  const theme = registry.themes.find((item) => item.name === "studio-index")!;
  return <main className="theme-detail-page"><header className="site-header"><Link className="brand" href="/" aria-label="Coordiation CSS home"><img src="/coordiation-logo.png" alt="" /><span>Coordiation</span><span className="brand-product">Themes</span></Link><nav aria-label="Main navigation"><Link href="/themes">All themes</Link><Link href="/blogs">Blogs</Link><Link href="/components">Components</Link><Link href="/icons">Icons</Link><Link href="/docs/themes">Docs</Link></nav><MobileNav /><Link className="header-cta" href={theme.preview}>Full preview <SolarIcon name="arrow-to-top-right" size={15} /></Link></header>
    <section className="theme-detail-hero studio-index-detail"><div><p className="component-overline">THEME 007 · {theme.status.toUpperCase()}</p><h1>{theme.title}</h1><p>{theme.description} It pairs a spacious project index with detailed, story-led case-study pages in one original, responsive Coordiation application.</p><div className="theme-tags">{theme.categories.map((category)=><span key={category}>{category}</span>)}</div></div><div><ThemeCommand command={theme.command} /><small>The CLI installs the portfolio index, reusable case-study route, shared data source, components, Solar icon wrapper, and twelve self-hosted photographs.</small></div></section>
    <section className="theme-preview-frame"><div className="theme-browser-bar"><span><i/><i/><i/></span><code>/studio-index</code><Link href={theme.preview}>Open full screen <SolarIcon name="arrow-to-top-right" size={14}/></Link></div><iframe src={theme.preview} title="Studio Index live theme preview" loading="eager" /></section>
    <section className="theme-detail-spec"><div><p className="component-overline">PORTFOLIO + CASE STUDIES</p><h2>{theme.sections.length} complete surfaces</h2><p>One reusable project data source drives the home index, six detail pages, page-specific metadata, visual systems, galleries, and outcomes.</p></div><ol>{theme.sections.map((section,index)=><li key={section}><span>{String(index+1).padStart(2,"0")}</span><b>{section}</b></li>)}</ol></section>
    <section className="theme-detail-files"><div><p className="component-overline">COORDIATION-NATIVE</p><h2>Minimal portfolio.<br />Full case-study depth.</h2></div><div><h3>Installed files</h3>{theme.files.map(file=><code key={file.target}>{file.target}</code>)}<h3>Bundled primitives</h3>{theme.components.map(component=><code key={component}>{component}</code>)}</div><aside><SolarIcon name="code" size={26}/><p>The theme uses {theme.coordiationUtilityCount} verified <code>co-*</code> utilities, a bundled <code>ThemeIcon</code>, reusable Coordiation primitives, and the <code>{theme.namespace}</code> namespace.</p><a href={theme.installPath}>Inspect registry item <SolarIcon name="arrow-to-top-right" size={14} /></a></aside></section>
    <section className="theme-detail-cta"><p className="component-overline">READY TO SHARE</p><h2>Make every project easy to explore.</h2><p>Replace the identity, projects, stories, assets, and case-study details while preserving semantic structure, responsive behavior, Coordiation icons, motion safeguards, and Coordiation copyright.</p><ThemeCommand command={theme.command} /></section>
  </main>;
}
