import { createSeoMetadata } from "@/app/seo";
import type { Metadata } from "next";
import Link from "@/app/_components/SiteLink";
import MobileNav from "../../_components/MobileNav";
import SolarIcon from "../../_components/SolarIcon";
import registry from "../../docs/generated/theme-registry.json";
import ThemeCommand from "../ThemeCommand";

export const metadata: Metadata = createSeoMetadata({ path: "/themes/serein-journal", title: "Serein Journal theme — Coordiation CSS", description: "Preview and install the Serein Journal open-code editorial magazine theme.", openGraph: { title: "Serein Journal — Coordiation Themes", description: "A spacious editorial magazine application built with Coordiation components and CSS utilities.", images: ["/themes/noir-habitat/project-interior.jpg"] }, twitter: { card: "summary_large_image", title: "Serein Journal — Coordiation Themes", description: "A refined editorial magazine for independent publishing.", images: ["/themes/noir-habitat/project-interior.jpg"] } });

export default function SereinJournalThemePage() {
  const theme = registry.themes.find((item) => item.name === "serein-journal")!;
  return <main className="theme-detail-page"><header className="site-header"><Link className="brand" href="/" aria-label="Coordiation CSS home"><img src="/coordiation-logo.png" alt="" /><span>Coordiation</span><span className="brand-product">Themes</span></Link><nav aria-label="Main navigation"><Link href="/themes">All themes</Link><Link href="/blogs">Blogs</Link><Link href="/components">Components</Link><Link href="/icons">Icons</Link><Link href="/docs/themes">Docs</Link></nav><MobileNav /><Link className="header-cta" href={theme.preview}>Full preview <SolarIcon name="arrow-to-top-right" size={15} /></Link></header>
    <section className="theme-detail-hero serein-journal-detail"><div><p className="component-overline">THEME 009 · {theme.status.toUpperCase()}</p><h1>{theme.title}</h1><p>{theme.description} It turns the reference’s airy magazine rhythm into an original, responsive Coordiation application with a calm Southeast Asian editorial voice.</p><div className="theme-tags">{theme.categories.map((category)=><span key={category}>{category}</span>)}</div></div><div><ThemeCommand command={theme.command} /><small>The CLI installs the complete journal page, reusable editorial components, Solar icon wrapper, responsive styles, and bundled media references.</small></div></section>
    <section className="theme-preview-frame"><div className="theme-browser-bar"><span><i/><i/><i/></span><code>/serein-journal</code><Link href={theme.preview}>Open full screen <SolarIcon name="arrow-to-top-right" size={14}/></Link></div><iframe src={theme.preview} title="Serein Journal live theme preview" loading="eager" /></section>
    <section className="theme-detail-spec"><div><p className="component-overline">EDITORIAL SYSTEM</p><h2>{theme.sections.length} complete sections</h2><p>A complete magazine front page covering discovery, feature storytelling, curated reading, the archive, newsletter conversion, and a structured footer.</p></div><ol>{theme.sections.map((section,index)=><li key={section}><span>{String(index+1).padStart(2,"0")}</span><b>{section}</b></li>)}</ol></section>
    <section className="theme-detail-files"><div><p className="component-overline">COORDIATION-NATIVE</p><h2>Editorial restraint.<br />Inspectable structure.</h2></div><div><h3>Installed files</h3>{theme.files.map(file=><code key={file.target}>{file.target}</code>)}<h3>Bundled primitives</h3>{theme.components.map(component=><code key={component}>{component}</code>)}</div><aside><SolarIcon name="code" size={26}/><p>The theme uses {theme.coordiationUtilityCount} verified <code>co-*</code> utilities, a bundled <code>ThemeIcon</code>, reusable Coordiation primitives, and the <code>{theme.namespace}</code> namespace.</p><a href={theme.installPath}>Inspect registry item <SolarIcon name="arrow-to-top-right" size={14} /></a></aside></section>
    <section className="theme-detail-cta"><p className="component-overline">READY TO PUBLISH</p><h2>Give your stories room to stay.</h2><p>Replace the publication identity, categories, articles, imagery, and newsletter details while preserving the accessible navigation, responsive hierarchy, Coordiation icons, motion safeguards, and Coordiation copyright.</p><ThemeCommand command={theme.command} /></section>
  </main>;
}
