import { createSeoMetadata } from "@/app/seo";
import type { Metadata } from "next";
import Link from "@/app/_components/SiteLink";
import MobileNav from "../../_components/MobileNav";
import SolarIcon from "../../_components/SolarIcon";
import registry from "../../docs/generated/theme-registry.json";
import ThemeCommand from "../ThemeCommand";

export const metadata: Metadata = createSeoMetadata({ path: "/themes/industrial-forge", title: "Industrial Forge theme — Coordiation CSS", description: "Preview and install the Industrial Forge open-code engineering company theme.", openGraph: { title: "Industrial Forge — Coordiation Themes", description: "A bold industrial engineering company website built with Coordiation components and CSS utilities.", images: ["/themes/industrial-forge/hero.jpg"] }, twitter: { card: "summary_large_image", title: "Industrial Forge — Coordiation Themes", description: "A bold industrial engineering company website built with Coordiation.", images: ["/themes/industrial-forge/hero.jpg"] } });

export default function IndustrialForgeThemePage() {
  const theme = registry.themes.find((item) => item.name === "industrial-forge")!;
  return <main className="theme-detail-page"><header className="site-header"><Link className="brand" href="/" aria-label="Coordiation CSS home"><img src="/coordiation-logo.png" alt="" /><span>Coordiation</span><span className="brand-product">Themes</span></Link><nav aria-label="Main navigation"><Link href="/themes">All themes</Link><Link href="/blogs">Blogs</Link><Link href="/components">Components</Link><Link href="/icons">Icons</Link><Link href="/docs/themes">Docs</Link></nav><MobileNav /><Link className="header-cta" href={theme.preview}>Full preview <SolarIcon name="arrow-to-top-right" size={15} /></Link></header>
    <section className="theme-detail-hero industrial-forge-detail"><div><p className="component-overline">THEME 004 · {theme.status.toUpperCase()}</p><h1>{theme.title}</h1><p>{theme.description} It translates the rhythm of industrial editorial design into an original, accessible, production-ready Coordiation application.</p><div className="theme-tags">{theme.categories.map((category)=><span key={category}>{category}</span>)}</div></div><div><ThemeCommand command={theme.command} /><small>The CLI installs the complete page, stylesheet, Coordiation primitives, Solar icon component, and six self-hosted industrial photographs.</small></div></section>
    <section className="theme-preview-frame"><div className="theme-browser-bar"><span><i/><i/><i/></span><code>/industrial-forge</code><Link href={theme.preview}>Open full screen <SolarIcon name="arrow-to-top-right" size={14}/></Link></div><iframe src={theme.preview} title="Industrial Forge live theme preview" loading="eager" /></section>
    <section className="theme-detail-spec"><div><p className="component-overline">STRUCTURE</p><h2>{theme.sections.length} complete sections</h2><p>Every region is declared in the registry, making the theme straightforward for teams and AI agents to inspect, customize, and track.</p></div><ol>{theme.sections.map((section,index)=><li key={section}><span>{String(index+1).padStart(2,"0")}</span><b>{section}</b></li>)}</ol></section>
    <section className="theme-detail-files"><div><p className="component-overline">COORDIATION-NATIVE</p><h2>Industrial character.<br />Inspectable source.</h2></div><div><h3>Installed files</h3>{theme.files.map(file=><code key={file.target}>{file.target}</code>)}<h3>Bundled primitives</h3>{theme.components.map(component=><code key={component}>{component}</code>)}</div><aside><SolarIcon name="code" size={26}/><p>The theme uses {theme.coordiationUtilityCount} verified <code>co-*</code> utilities, a bundled <code>ThemeIcon</code>, reusable Coordiation UI primitives, and the <code>{theme.namespace}</code> namespace.</p><a href={theme.installPath}>Inspect registry item <SolarIcon name="arrow-to-top-right" size={14} /></a></aside></section>
    <section className="theme-detail-cta"><p className="component-overline">READY TO ENGINEER</p><h2>Turn the reference into your own system.</h2><p>Replace the company identity, services, projects, and imagery while preserving semantic structure, responsive behavior, Coordiation icons, and Coordiation copyright.</p><ThemeCommand command={theme.command} /></section>
  </main>;
}
