import { createSeoMetadata } from "@/app/seo";
import type { Metadata } from "next";
import Link from "@/app/_components/SiteLink";
import MobileNav from "../_components/MobileNav";
import SolarIcon from "../_components/SolarIcon";
import registry from "../docs/generated/theme-registry.json";
import ThemeCommand from "./ThemeCommand";

export const metadata: Metadata = createSeoMetadata({ path: "/themes", ...{
  title: "Application themes — Coordiation CSS",
  description: "Preview and install complete open-code application templates built for Coordiation CSS.",
} });

export default function ThemesPage() {
  const showcase = {
    "editorial-advisor": { mark: "MA", headline: <>Editorial confidence.<br />Human warmth.</>, copy: "A complete consultant portfolio with an editorial hero, events, insights, client story, biography, capabilities, statistics, and a focused contact close.", alt: "Editorial Advisor template portrait preview" },
    "quiet-journal": { mark: "QJ", headline: <>Thoughtful stories.<br />A gentler rhythm.</>, copy: "An illustrated personal journal with a welcoming hero, writer profile, featured essays, archive grid, topic browser, and a newsletter designed for meaningful connection.", alt: "Quiet Journal illustrated writing desk preview" },
    "finance-dashboard": { mark: "FD", headline: <>Financial clarity.<br />Operational rhythm.</>, copy: "A complete finance operations dashboard with Coordiation cards, buttons, badges, avatars, accessible tables, CSS-native charts, transaction history, and collaborator payouts.", alt: "Finance Dashboard interface preview" },
    "industrial-forge": { mark: "IF", headline: <>Industrial confidence.<br />Field-tested clarity.</>, copy: "A complete engineering company site with a photographic hero, services, delivery process, project index, proof, insights, contact CTA, and a responsive navigation system.", alt: "Industrial Forge engineering company preview" },
    "mono-portfolio": { mark: "MP", headline: <>Creative structure.<br />Electric character.</>, copy: "A complete designer portfolio with a modular hero, moving service marquee, case studies, services, pricing, testimonials, FAQ, journal, and a high-contrast responsive system.", alt: "Mono Portfolio creative designer preview" },
    "noir-habitat": { mark: "NH", headline: <>Architectural calm.<br />Cinematic precision.</>, copy: "A complete architecture studio site with an image-led hero, manifesto, services, residential portfolio, interior studies, process, testimonial, newsletter, journal, and responsive navigation.", alt: "Noir Habitat dark architecture studio preview" },
  } as const;
  return <main className="themes-page">
    <header className="site-header"><Link className="brand" href="/" aria-label="Coordiation CSS home"><img src="/coordiation-logo.png" alt="" /><span>Coordiation</span><span className="brand-product">Themes</span></Link><nav aria-label="Main navigation"><Link href="/">Home</Link><Link href="/components">Components</Link><Link href="/icons">Icons</Link><Link href="/docs/themes">Theme guide</Link><Link href="/release-check">Release Check</Link></nav><MobileNav /><a className="header-cta" href="#theme-catalog">Browse themes <SolarIcon name="arrow-down" size={15} /></a></header>
    <section className="themes-hero"><div><p className="component-overline">FULL APPLICATIONS · OPEN CODE · AI-READABLE</p><h1>Start with a<br /><em>complete story.</em></h1><p>Install complete, responsive application templates—not opaque presets. Each theme includes editable source, documented sections, original media, design tokens, and a machine-readable contract.</p><div className="themes-hero-actions"><a href="#theme-catalog">Explore the theme library <SolarIcon name="arrow-right" size={16} /></a><Link href="/docs/themes">How installation works</Link></div></div><div className="themes-hero-index"><span>CURATED LIBRARY</span><strong>{String(registry.themeCount).padStart(2,"0")}</strong><p>Original application templates ready to preview and install.</p><div><b>Next.js</b><b>Responsive</b><b>Owned source</b></div></div></section>
    <section className="theme-catalog" id="theme-catalog">{registry.themes.map((theme, index) => { const presentation = showcase[theme.name as keyof typeof showcase]; return <div className="theme-catalog-entry" key={theme.name}><div className="theme-catalog-heading"><div><p className="component-overline">THEME {String(index + 1).padStart(3,"0")}</p><h2>{theme.title}</h2></div><p>{theme.description}</p></div><article className={`theme-showcase-card${index % 2 ? " is-reverse" : ""}`}><Link className="theme-cover" href={`/themes/${theme.name}`}>{theme.cover ? <img src={theme.cover} alt={presentation.alt} /> : <div className="theme-dashboard-cover" role="img" aria-label={presentation.alt}><aside><b>NL</b><i/><i/><i/><i/><i/></aside><section><header/><div><article/><article/><article/></div><main><span/><span/><span/><span/><span/><span/><span/></main></section></div>}<span>{theme.palette}</span><strong>{presentation.mark}</strong></Link><div className="theme-showcase-copy"><div className="theme-meta"><span>{theme.framework}</span><span>{theme.sections.length} sections</span><span>{theme.status}</span></div><h3>{presentation.headline}</h3><p>{presentation.copy}</p><div className="theme-tags">{theme.categories.map((category)=><span key={category}>{category}</span>)}</div><ThemeCommand command={theme.command} /><div className="theme-card-actions"><Link href={`/themes/${theme.name}`}>View details <SolarIcon name="arrow-right" size={15} /></Link><Link href={theme.preview}>Open live preview <SolarIcon name="arrow-to-top-right" size={15} /></Link></div></div></article></div>;})}</section>
    <section className="theme-ai-strip"><div><p className="component-overline">FOR PEOPLE + AGENTS</p><h2>Every choice stays inspectable.</h2></div><p>Query <code>/theme-registry.json</code> to discover exact theme names, files, sections, assets, installation endpoints, and customization rules without guessing.</p><a href="/theme-registry.json">Open JSON registry <SolarIcon name="arrow-to-top-right" size={16} /></a></section>
  </main>;
}
