import type { Metadata } from "next";
import Link from "@/app/_components/SiteLink";
import CodeBlock from "../_components/CodeBlock";
import registry from "../generated/theme-registry.json";

export const metadata: Metadata = { title: "Application themes", description: "Discover, install, and safely customize complete Coordiation application templates." };

export default function ThemeGuidePage() {
  return <article className="docs-article vite-guide">
    <div className="docs-breadcrumb"><Link prefetch={false} href="/docs">Docs</Link><b>/</b><span>Themes</span></div>
    <p className="docs-overline">OPEN-CODE APPLICATIONS · {registry.themeCount} STABLE THEMES</p><h1>Application themes</h1>
    <p className="docs-lead">Themes are complete application starting points, not color presets. Each entry combines responsive page source, Coordiation component primitives, design tokens, optional original media, a live preview, an install endpoint, and a machine-readable customization contract.</p>
    <div className="docs-note"><span>i</span><p>The source becomes part of your repository. There is no theme runtime, account, or visual builder required.</p></div>
    <div className="family-support"><span>See the finished application first.</span><Link prefetch={false} href="/themes">Browse theme previews →</Link></div>

    <section className="guide-step"><div className="step-number">01</div><div><h2>Install Coordiation CSS</h2><CodeBlock title="Terminal" code="npm install @coordiation/css @coordiation/vite" /><p>Configure the scanner for your application directory so literal Coordiation utilities inside installed themes are indexed with the rest of your project.</p></div></section>
    <section className="guide-step" id="install-theme"><div className="step-number">02</div><div><h2>Choose and install a theme</h2>{registry.themes.map((theme) => <div className="theme-doc-option" id={theme.name} key={theme.name}><h3>{theme.title}</h3><p>{theme.description}</p><CodeBlock title="Terminal" code={theme.command} /></div>)}<p>The official Coordiation CLI resolves the registry, checks every target path, refuses accidental overwrites, and writes the selected application into your project.</p></div></section>
    <section className="guide-step"><div className="step-number">03</div><div><h2>Use the bundled Coordiation primitives</h2><CodeBlock title="Theme components" code={registry.themes.map((theme) => `# ${theme.title}\n${theme.components.length ? theme.components.join("\n") : "ThemeIcon + semantic page sections"}`).join("\n\n")} /><p>Complex themes can bundle first-party Card, Button, Badge, Avatar, Input, Progress, Select, Table, and related primitives. Their source stays editable and their layout remains expressed with literal <code>co-*</code> utilities.</p></div></section>
    <section className="guide-step"><div className="step-number">04</div><div><h2>Bring the media with you</h2><CodeBlock title="Theme assets" code={registry.themes.map((theme) => `# ${theme.title}\n${theme.assets.length ? theme.assets.join("\n") : "No external media — CSS-only visual system"}`).join("\n\n")} /><p>The CLI downloads every declared public asset automatically. CSS-only themes need no copied media; illustrated themes can be self-hosted as installed or use your own optimized replacements.</p></div></section>
    <section className="guide-step"><div className="step-number">05</div><div><h2>Replace identity before layout</h2><CodeBlock title="Recommended edit order" code={"1. Brand, author identity, biography, and contact details\n2. Hero and content imagery\n3. Stories, events, statistics, metrics, and calls to action\n4. Theme-specific CSS variables\n5. Section order and optional sections"} /><p>Each registry record declares its exact wrapper namespace and class prefix. Reusable layout, control, and alignment primitives remain literal <code>co-*</code> utilities.</p></div></section>
    <section className="guide-step"><div className="step-number">06</div><div><h2>Let AI inspect the contract</h2><CodeBlock title="Discovery endpoints" code={`GET /theme-registry.json\nGET /r/themes/registry.json\n${registry.themes.map((theme) => `GET ${theme.installPath}`).join("\n")}`} /><p>Use the extended manifest to select exact files, sections, assets, components, utilities, and customization rules. Do not infer theme names or reconstruct a template from its screenshot.</p></div></section>
    <section className="family-caveats"><div><p className="docs-overline">SAFE CUSTOMIZATION</p><h2>Keep what makes it dependable</h2><p>The template is yours, but a few structural choices protect accessibility and maintainability.</p></div><ul><li>Preserve the heading hierarchy and descriptive image alternatives.</li><li>Keep focusable navigation, buttons, forms, and contact actions semantic.</li><li>Retain literal co-* utilities and the declared theme namespace.</li><li>Use ThemeIcon and exact SVG assets from the Coordiation icon registry.</li><li>Keep the footer copyright credited to Coordiation in every template.</li><li>Use original or properly licensed replacement media.</li><li>Test all breakpoints after changing copy length or section order.</li></ul></section>
    <div className="docs-next split"><Link prefetch={false} href="/themes"><span>Interactive showcase</span><b>← Browse themes</b></Link><Link prefetch={false} href="/docs/components"><span>Build the interface</span><b>Component registry →</b></Link></div>
  </article>;
}
