import type { Metadata } from "next";
import ThemeIcon from "./ThemeIcon";
import { AgencyButton, BlogCard, PlanCard, ProjectCard, SectionHeading, ServiceCard, TeamCard, TestimonialCard } from "./DashboardComponents";
import "./signal-agency.css";

export const metadata: Metadata = { title: "Signal Agency — Digital Growth Studio", description: "A high-contrast digital agency theme built with Coordiation components, icons, and utilities." };

const team = [
  ["Ana Mahesa", "Strategy Director", "team-ana.jpg"], ["Raka Putra", "Product Lead", "team-raka.jpg"],
  ["Nadia Kirana", "Creative Director", "team-nadia.jpg"], ["Bima Arwana", "Engineering Lead", "team-bima.jpg"],
];

export default function SignalAgencyPreview() {
  return <main className="signal-agency co-overflow-hidden" id="top">
    <header className="sa-header co-flex co-items-center co-justify-between"><a className="sa-logo co-flex co-items-center" href="#top"><span>Signal</span><i /></a><nav className="co-flex co-items-center" aria-label="Signal Agency navigation"><a href="#about">About</a><a href="#services">Services</a><a href="#work">Projects</a><a href="#team">Team</a><a href="#journal">Journal</a></nav><AgencyButton href="#contact">Start a project</AgencyButton><details className="sa-mobile-menu"><summary aria-label="Open navigation"><ThemeIcon name="hamburger-menu" size={22} tone="accent" /></summary><div className="co-flex co-flex-col"><a href="#about">About</a><a href="#services">Services</a><a href="#work">Projects</a><a href="#team">Team</a><a href="#journal">Journal</a><a href="#contact">Start a project</a></div></details></header>

    <section className="sa-hero"><div className="sa-hero-title"><p className="sa-kicker co-flex co-items-center"><i className="motion-safe:co-animate-pulse motion-reduce:co-animate-none" />Digital growth partner</p><h1>Grow your digital<br /><em>signal.</em></h1><p>Strategy, design, and technology for ambitious teams building the next useful thing.</p><AgencyButton href="#work">Explore our work</AgencyButton></div><aside className="sa-hero-left co-grid"><div><ThemeIcon name="target" size={24} tone="accent" /><strong>50k+</strong><span>Qualified actions created</span></div><div><ThemeIcon name="graph-new-up" size={24} tone="accent" /><strong>4.8×</strong><span>Average growth impact</span></div></aside><figure className="sa-hero-image co-relative co-overflow-hidden"><img className="co-w-full co-h-full co-object-cover" src="/themes/signal-agency/hero-team.jpg" alt="Creative agency team collaborating around laptops" /><figcaption className="co-absolute co-flex co-items-center co-justify-between"><span>Jakarta · Singapore · Remote</span><b>EST. 2019</b></figcaption></figure><aside className="sa-hero-right co-flex co-flex-col"><a className="sa-play co-inline-flex co-items-center co-justify-center" href="#showreel" aria-label="Play agency showreel"><ThemeIcon name="play-circle" size={34} tone="accent" /></a><div><strong>25k</strong><span>Campaign outcomes tracked</span></div><p>Trusted by product teams across finance, mobility, health, and culture.</p></aside></section>

    <section className="sa-about co-grid" id="about"><div className="sa-about-collage co-grid"><img className="co-w-full co-h-full co-object-cover" src="/themes/signal-agency/about-team.jpg" alt="Creative team working together in a studio" /><div className="co-flex co-flex-col co-justify-between"><span>24/7 support</span><strong>One team from first signal to launch.</strong><ThemeIcon name="users-group-rounded" size={25} tone="accent" /></div></div><div><p className="sa-kicker co-flex co-items-center"><i />About us</p><h2>We’re a creative<br />digital studio.</h2><p>Signal brings brand strategy, product design, growth thinking, and development into one close working team. The result is clearer decisions and experiences people return to.</p><div className="sa-about-principles co-grid"><article><ThemeIcon name="target" size={23} tone="accent" /><h3>Our vision</h3><p>Make useful digital products feel unmistakably human.</p></article><article><ThemeIcon name="shield-check" size={23} tone="accent" /><h3>Our mission</h3><p>Turn complexity into a strong, measurable customer experience.</p></article></div><AgencyButton href="#services" outline>Discover Signal</AgencyButton></div></section>

    <section className="sa-services" id="services"><SectionHeading eyebrow="Services" title={<>Creative systems<br />that move business.</>} copy="We combine the disciplines needed to take an idea from strategy to a responsive, launch-ready experience." action={<AgencyButton href="#contact" outline>See all services</AgencyButton>} /><div className="sa-service-grid co-grid"><ServiceCard index="01" icon="monitor" title="Web experiences" copy="High-performing marketing sites shaped around a clear customer journey." image="/themes/signal-agency/project-product.jpg" /><ServiceCard index="02" icon="palette" title="Digital identity" copy="Flexible visual systems that make every product touchpoint recognizable." image="/themes/signal-agency/project-strategy.jpg" /><ServiceCard index="03" icon="code" title="Product interfaces" copy="Useful UX, robust UI patterns, and responsive frontend implementation." image="/themes/signal-agency/project-interface.jpg" /></div></section>

    <section className="sa-showreel co-relative co-flex co-items-center co-justify-center co-text-center" id="showreel"><img className="co-absolute co-w-full co-h-full co-object-cover" src="/themes/signal-agency/blog-meeting.jpg" alt="Team reviewing a digital strategy together" /><div className="co-absolute" /><div className="co-relative"><p className="sa-kicker co-flex co-items-center co-justify-center"><i />Connect</p><h2>Want to work<br />with us?</h2><a className="sa-play co-inline-flex co-items-center co-justify-center" href="#contact" aria-label="Contact Signal Agency"><ThemeIcon name="play-circle" size={42} tone="accent" /></a></div><footer className="co-absolute co-grid"><a className="co-flex co-items-center" href="tel:+62215550184"><ThemeIcon name="phone" size={18} tone="accent" /><span>Call for inquiry<small>+62 21 555 0184</small></span></a><a className="co-flex co-items-center" href="mailto:hello@signal.example"><ThemeIcon name="letter" size={18} tone="accent" /><span>Email for inquiry<small>hello@signal.example</small></span></a><AgencyButton href="#contact">Contact now</AgencyButton></footer></section>

    <section className="sa-benefits"><SectionHeading eyebrow="Why Signal" title={<>Crafting experiences.<br />Delivering success.</>} copy="Fast collaboration, direct access to specialists, and decisions that stay connected to the outcome." /><div className="sa-benefit-layout co-grid"><div className="sa-benefit-stack co-grid"><article><ThemeIcon name="graph-new-up" size={24} tone="accent" /><h3>Fast, reliable service</h3><p>Short feedback loops and visible delivery milestones.</p></article><article><ThemeIcon name="shield-check" size={24} tone="accent" /><h3>Ongoing support</h3><p>A familiar team remains available after launch.</p></article></div><figure className="co-relative co-overflow-hidden"><img className="co-w-full co-h-full co-object-cover" src="/themes/signal-agency/team-ana.jpg" alt="Signal Agency strategy director" /><figcaption className="co-absolute">A senior partner stays close to every project.</figcaption></figure><div className="sa-benefit-stack co-grid"><article><ThemeIcon name="users-group-rounded" size={24} tone="accent" /><h3>One integrated team</h3><p>Strategy, design, and engineering work from one brief.</p></article><article><ThemeIcon name="target" size={24} tone="accent" /><h3>Measurable outcomes</h3><p>Success measures are agreed before the first screen.</p></article></div></div></section>

    <section className="sa-work" id="work"><SectionHeading eyebrow="Projects" title={<>Work that ignites<br />business growth.</>} copy="A selection of brand, product, and campaign systems built around a real opportunity." action={<AgencyButton href="#contact" outline>More projects</AgencyButton>} /><div className="sa-project-grid co-grid"><ProjectCard wide category="Brand strategy" title="Voltase mobility platform" image="/themes/signal-agency/project-strategy.jpg" /><ProjectCard category="Product design" title="Nadi health companion" image="/themes/signal-agency/project-interface.jpg" /><ProjectCard category="Digital experience" title="Teras workspace" image="/themes/signal-agency/project-product.jpg" /></div><div className="sa-logo-row co-grid">{["NUSAPULSE","METRO LAB","SAGARA","NADI","KARYA GRID"].map((brand)=><span key={brand}>{brand}</span>)}</div></section>

    <section className="sa-pricing"><SectionHeading eyebrow="Pricing" title={<>Choose your<br />best plan.</>} copy="Clear starting points for different stages of growth. Every engagement is adapted after discovery." /><div className="sa-plan-grid co-grid"><PlanCard name="Foundation" price="129" /><PlanCard name="Growth" price="150" featured /><PlanCard name="Scale" price="199" /></div></section>

    <section className="sa-stats co-relative co-grid"><img className="co-absolute co-w-full co-h-full co-object-cover" src="/themes/signal-agency/about-team.jpg" alt="" /><div className="co-absolute" />{[["10k+","Useful actions"],["8k+","Qualified leads"],["98%","Client retention"],["25+","Years combined"]].map(([value,label])=><article className="co-relative co-text-center" key={label}><strong>{value}</strong><span>{label}</span></article>)}</section>

    <section className="sa-team" id="team"><div className="sa-team-intro"><p className="sa-kicker co-flex co-items-center"><i />Our team</p><h2>Small senior team.<br />Serious range.</h2><p>Meet the people who turn strategy into useful interfaces, scalable systems, and measurable growth.</p><AgencyButton href="#contact" outline>Meet everyone</AgencyButton></div><div className="sa-team-grid co-grid">{team.map(([name,role,image])=><TeamCard key={name} name={name} role={role} image={`/themes/signal-agency/${image}`} />)}</div></section>

    <section className="sa-testimonials"><SectionHeading eyebrow="Testimonials" title={<>What clients<br />say about Signal.</>} copy="Long-term partnerships built on clear thinking, responsive collaboration, and work that performs." /><div className="sa-quote-grid co-grid"><TestimonialCard quote="They turned a scattered brief into a product story our entire company could finally believe in." name="Julian Tan" role="Founder, Nadi" /><TestimonialCard quote="Signal moved quickly without making the work feel rushed. Every decision had a reason and a measure." name="Mira Halim" role="VP Growth, Voltase" /><TestimonialCard quote="The system is still easy for our internal team to use, which is the clearest sign they built it properly." name="David Putra" role="Director, Teras" /></div></section>

    <section className="sa-journal" id="journal"><SectionHeading eyebrow="From the studio" title={<>A glance at our<br />latest thinking.</>} copy="Practical notes on useful products, strong identities, and building growth systems that last." action={<AgencyButton href="#contact" outline>View journal</AgencyButton>} /><div className="sa-blog-grid co-grid"><BlogCard image="/themes/signal-agency/blog-meeting.jpg" date="Aug 24, 2026" category="Strategy" title="Managing the way your team measures success" /><BlogCard image="/themes/signal-agency/project-product.jpg" date="Aug 12, 2026" category="Design systems" title="Why clarity makes digital experiences feel faster" /><BlogCard image="/themes/signal-agency/project-interface.jpg" date="Jul 28, 2026" category="Product" title="Creating interfaces people can learn without friction" /></div></section>

    <section className="sa-contact co-grid co-items-center" id="contact"><div><p className="sa-kicker co-flex co-items-center"><i />Next project</p><h2>Want to work<br />with Signal?</h2><p>Tell us what you are building and where the opportunity feels stuck.</p><div className="co-flex co-items-center"><AgencyButton href="mailto:hello@signal.example">Start the conversation</AgencyButton><a className="sa-contact-play co-inline-flex co-items-center" href="#showreel"><ThemeIcon name="play-circle" size={35} tone="accent" />Watch showreel</a></div></div><img className="co-w-full co-h-full co-object-cover" src="/themes/signal-agency/hero-team.jpg" alt="Signal Agency team" /></section>

    <footer className="sa-footer"><div className="sa-footer-grid co-grid"><div><a className="sa-logo co-flex co-items-center" href="#top"><span>Signal</span><i /></a><p>Independent digital studio helping ambitious teams build clear, useful, and measurable experiences.</p></div><div><strong>Quick links</strong><a href="#about">About</a><a href="#services">Services</a><a href="#work">Projects</a><a href="#journal">Journal</a></div><div><strong>Services</strong><a href="#services">Brand strategy</a><a href="#services">Product design</a><a href="#services">Web development</a><a href="#services">Growth systems</a></div><div><strong>Contact</strong><a href="mailto:hello@signal.example">hello@signal.example</a><a href="tel:+62215550184">+62 21 555 0184</a><span>Jakarta · Singapore</span></div></div><div className="sa-footer-bottom co-flex co-items-center co-justify-between"><span>© 2026 Coordiation. All rights reserved.</span><div className="co-flex co-items-center"><a href="#top">Back to top</a><ThemeIcon name="arrow-to-top-right" size={14} tone="accent" /></div></div></footer>
  </main>;
}
