import { createSeoMetadata } from "@/app/seo";
import type { Metadata } from "next";
import Link from "@/app/_components/SiteLink";
import MobileNav from "../../_components/MobileNav";
import SolarIcon from "../../_components/SolarIcon";
import registry from "../../docs/generated/theme-registry.json";
import ThemeCommand from "../ThemeCommand";

export const metadata: Metadata = createSeoMetadata({ path: "/themes/signal-agency", title: "Signal Agency theme — Coordiation CSS", description: "Preview and install the Signal Agency open-code digital studio theme.", openGraph: { title: "Signal Agency — Coordiation Themes", description: "A dark, electric-lime digital agency application built with Coordiation components and CSS utilities.", images: ["/themes/signal-agency/hero-team.jpg"] }, twitter: { card: "summary_large_image", title: "Signal Agency — Coordiation Themes", description: "A high-contrast digital agency site for strategy, design, and development teams.", images: ["/themes/signal-agency/hero-team.jpg"] } });

export default function SignalAgencyThemePage() {
  const theme = registry.themes.find((item) => item.name === "signal-agency")!;
  return <main className="theme-detail-page"><header className="site-header"><Link className="brand" href="/" aria-label="Coordiation CSS home"><img src="/coordiation-logo.png" alt="" /><span>Coordiation</span><span className="brand-product">Themes</span></Link><nav aria-label="Main navigation"><Link href="/themes">All themes</Link><Link href="/blogs">Blogs</Link><Link href="/components">Components</Link><Link href="/icons">Icons</Link><Link href="/docs/themes">Docs</Link></nav><MobileNav /><Link className="header-cta" href={theme.preview}>Full preview <SolarIcon name="arrow-to-top-right" size={15} /></Link></header>
    <section className="theme-detail-hero signal-agency-detail"><div><p className="component-overline">THEME 008 · {theme.status.toUpperCase()}</p><h1>{theme.title}</h1><p>{theme.description} It translates the reference’s energetic dark-and-lime rhythm into an original, responsive Coordiation application for creative and digital teams.</p><div className="theme-tags">{theme.categories.map((category)=><span key={category}>{category}</span>)}</div></div><div><ThemeCommand command={theme.command} /><small>The CLI installs the full landing page, reusable agency components, Solar icon wrapper, responsive styles, and ten self-hosted photographs.</small></div></section>
    <section className="theme-preview-frame"><div className="theme-browser-bar"><span><i/><i/><i/></span><code>/signal-agency</code><Link href={theme.preview}>Open full screen <SolarIcon name="arrow-to-top-right" size={14}/></Link></div><iframe src={theme.preview} title="Signal Agency live theme preview" loading="eager" /></section>
    <section className="theme-detail-spec"><div><p className="component-overline">DIGITAL STUDIO SYSTEM</p><h2>{theme.sections.length} complete sections</h2><p>A modular agency experience covering positioning, services, work, commercial packages, proof, people, thinking, and conversion.</p></div><ol>{theme.sections.map((section,index)=><li key={section}><span>{String(index+1).padStart(2,"0")}</span><b>{section}</b></li>)}</ol></section>
    <section className="theme-detail-files"><div><p className="component-overline">COORDIATION-NATIVE</p><h2>Electric energy.<br />Inspectible structure.</h2></div><div><h3>Installed files</h3>{theme.files.map(file=><code key={file.target}>{file.target}</code>)}<h3>Bundled primitives</h3>{theme.components.map(component=><code key={component}>{component}</code>)}</div><aside><SolarIcon name="code" size={26}/><p>The theme uses {theme.coordiationUtilityCount} verified <code>co-*</code> utilities, a bundled <code>ThemeIcon</code>, reusable Coordiation primitives, and the <code>{theme.namespace}</code> namespace.</p><a href={theme.installPath}>Inspect registry item <SolarIcon name="arrow-to-top-right" size={14} /></a></aside></section>
    <section className="theme-detail-cta"><p className="component-overline">READY TO GROW</p><h2>Give your agency a stronger signal.</h2><p>Replace the identity, services, projects, pricing, people, insights, and contact information while preserving the responsive system, accessible navigation, Coordiation icons, motion safeguards, and Coordiation copyright.</p><ThemeCommand command={theme.command} /></section>
  </main>;
}
