import type { Metadata } from "next";
import ThemeIcon from "./ThemeIcon";
import { ArticleCard, ProcessStep, ProjectCard, SectionTitle, StudioButton } from "./DashboardComponents";
import "./noir-habitat.css";

export const metadata: Metadata = { title: "Noir Habitat — Architecture & Interiors", description: "An original dark editorial architecture studio theme built with Coordiation." };

const serviceNames = ["Architecture", "Interior", "Landscape", "Spatial strategy"];

const process = [
  ["01", "Listen", "We document the people, rituals, place, budget, and ambitions that should shape the project.", "eye"],
  ["02", "Frame", "A clear brief turns constraints into a shared design direction and an honest project roadmap.", "layers-minimalistic"],
  ["03", "Design", "Plans, material studies, models, and prototypes make every important decision visible early.", "ruler-pen"],
  ["04", "Deliver", "We coordinate details, consultants, and site observations through construction and handover.", "shield-check"],
] as const;

export default function NoirHabitatPreview() {
  return <main className="noir-habitat co-overflow-hidden" id="top">
    <header className="nh-header co-flex co-items-center co-justify-between"><a className="nh-brand co-inline-flex co-items-center" href="#top"><b>N/H</b><span>Noir Habitat<small>Architecture &amp; interiors</small></span></a><nav className="co-flex co-items-center"><a href="#studio">Studio</a><a href="#services">Services</a><a href="#work">Work</a><a href="#contact">Contact</a></nav><StudioButton href="#contact">Start a project</StudioButton><details><summary aria-label="Open navigation"><ThemeIcon name="hamburger-menu" size={22} /></summary><div><a href="#studio">Studio</a><a href="#services">Services</a><a href="#work">Work</a><a href="#contact">Contact</a></div></details></header>
    <section className="nh-hero co-grid co-items-center"><aside><span>Established 2013</span><p>Jakarta · Singapore<br />Architecture for tropical life.</p></aside><div><p className="nh-kicker">Architecture shaped by light, material, and place.</p><h1>Spaces with<br />quiet strength.</h1><StudioButton href="#work">Explore our work</StudioButton></div><figure className="co-relative co-overflow-hidden"><img className="co-w-full co-h-full co-object-cover" src="/themes/noir-habitat/hero.jpg" alt="Modern forest house by Noir Habitat" /><figcaption className="co-absolute co-flex co-items-center co-justify-between"><span>Canopy House · Bandung</span><ThemeIcon name="arrow-to-top-right" size={16} /></figcaption></figure></section>
    <section className="nh-manifesto co-grid" id="studio"><div><SectionTitle overline="Studio">We design for<br />how life unfolds.</SectionTitle><p>Noir Habitat is an independent architecture and interior studio creating calm, enduring places across Southeast Asia.</p></div><article><strong>01</strong><h3>Observe</h3><p>Read the site, climate, rituals, and constraints before drawing the first line.</p></article><article><strong>02</strong><h3>Refine</h3><p>Reduce every decision until structure, material, and atmosphere feel inevitable.</p></article></section>

    <section className="nh-service-strip" id="services"><div className="nh-service-track co-flex co-items-center">{[...serviceNames,...serviceNames].map((name,index)=><span className="co-flex co-items-center" key={`${name}-${index}`}>{name}<i /></span>)}</div></section>

    <section className="nh-services nh-shell"><SectionTitle overline="Services">From structure<br />to atmosphere.</SectionTitle><div className="nh-services-grid co-grid"><article className="nh-service-image co-relative co-overflow-hidden"><img className="co-w-full co-h-full co-object-cover co-transition co-duration-500 co-ease-out" src="/themes/noir-habitat/service-exterior.jpg" alt="Dark modern exterior surrounded by trees" /><span className="co-absolute">01 · Architecture</span></article><article className="nh-service-feature co-flex co-flex-col"><ThemeIcon name="sofa-2" size={42} tone="sand" /><h3>Interior</h3><p>Material, light, furniture, and movement composed as one continuous experience.</p><StudioButton href="#contact">Explore service</StudioButton></article><article className="nh-service-image co-relative co-overflow-hidden"><img className="co-w-full co-h-full co-object-cover co-transition co-duration-500 co-ease-out" src="/themes/noir-habitat/service-interior.jpg" alt="Warm minimal residential interior" /><span className="co-absolute">02 · Interior</span></article></div></section>

    <section className="nh-work nh-shell" id="work"><div className="nh-heading-row co-flex co-items-end co-justify-between"><SectionTitle overline="Selected work">Homes shaped<br />around place.</SectionTitle><p>Each project responds to climate, landscape, and the small routines that make a space feel personal.</p></div><div className="nh-project-grid co-grid"><ProjectCard image="/themes/noir-habitat/project-house.jpg" title="Canopy House" category="Bandung · Residence" wide /><ProjectCard image="/themes/noir-habitat/project-villa.jpg" title="Stone Courtyard Villa" category="Bali · Hospitality" /><ProjectCard image="/themes/noir-habitat/project-interior.jpg" title="Lightwell Residence" category="Jakarta · Interior" /></div><div className="nh-work-action co-flex co-justify-center"><StudioButton href="#contact">View all projects</StudioButton></div></section>

    <section className="nh-interiors"><div className="nh-shell"><div className="nh-heading-row co-flex co-items-end co-justify-between"><SectionTitle overline="Interior studies">Material, shadow,<br />and daily ritual.</SectionTitle><div className="nh-view-switch co-flex"><button aria-label="Grid view"><ThemeIcon name="gallery-minimalistic" size={18} /></button><button aria-label="Layer view"><ThemeIcon name="layers-minimalistic" size={18} /></button></div></div><div className="nh-interior-grid co-grid"><figure className="co-relative co-overflow-hidden"><img className="co-w-full co-h-full co-object-cover co-transition co-duration-500 co-ease-out" src="/themes/noir-habitat/project-interior.jpg" alt="Minimal living space with warm wood" /><figcaption className="co-absolute">Quiet living · Jakarta</figcaption></figure><figure className="co-relative co-overflow-hidden"><img className="co-w-full co-h-full co-object-cover co-transition co-duration-500 co-ease-out" src="/themes/noir-habitat/news-material.jpg" alt="Material-focused residential interior" /><figcaption className="co-absolute">Soft material · Ubud</figcaption></figure><figure className="co-relative co-overflow-hidden"><img className="co-w-full co-h-full co-object-cover co-transition co-duration-500 co-ease-out" src="/themes/noir-habitat/news-light.jpg" alt="Architectural interior shaped by daylight" /><figcaption className="co-absolute">Filtered light · Surabaya</figcaption></figure></div></div></section>

    <section className="nh-process nh-shell"><div className="nh-heading-row co-flex co-items-end co-justify-between"><SectionTitle overline="Work process">Clear steps.<br />Shared decisions.</SectionTitle><StudioButton href="#contact">Discuss a project</StudioButton></div><div className="nh-process-layout co-grid"><div>{process.map(([number,title,copy,icon])=><ProcessStep number={number} title={title} copy={copy} icon={icon} key={number} />)}</div><figure className="co-relative co-overflow-hidden"><img className="co-w-full co-h-full co-object-cover" src="/themes/noir-habitat/process.jpg" alt="Architect reviewing drawings at a studio desk" /><figcaption className="co-absolute">Every decision stays visible from brief to handover.</figcaption></figure></div></section>

    <section className="nh-testimonial co-grid co-items-center"><div><ThemeIcon name="stars" size={28} tone="sand" /><blockquote>“The home feels calm, precise, and completely ours. Noir Habitat listened beyond our words and translated the way we live into every room.”</blockquote><div className="co-flex co-items-center"><img src="/themes/noir-habitat/testimonial.jpg" alt="Amara Wijaya, Noir Habitat client" /><p><b>Amara Wijaya</b><small>Canopy House client</small></p></div></div><aside><strong>4.9</strong><span>average partner rating</span><p>32 completed residential and hospitality projects across Southeast Asia.</p></aside></section>

    <section className="nh-newsletter"><div className="nh-shell co-grid co-items-center"><div><small>Notes from the studio</small><h2>Ideas for living<br />with more intention.</h2></div><form className="co-flex co-items-center"><ThemeIcon name="letter" size={18} /><label className="sr-only" htmlFor="nh-email">Email address</label><input id="nh-email" type="email" placeholder="Your email address" /><button type="submit">Subscribe <ThemeIcon name="arrow-right" size={14} tone="dark" /></button></form></div></section>

    <section className="nh-journal nh-shell"><div className="nh-heading-row co-flex co-items-end co-justify-between"><SectionTitle overline="Journal">Details worth<br />noticing.</SectionTitle><StudioButton href="#contact">More stories</StudioButton></div><div className="nh-article-grid co-grid"><ArticleCard image="/themes/noir-habitat/news-material.jpg" date="August 18, 2026" title="Five materials that age with quiet confidence" /><ArticleCard image="/themes/noir-habitat/news-light.jpg" date="August 09, 2026" title="Designing daylight for tropical homes" /><ArticleCard image="/themes/noir-habitat/project-villa.jpg" date="July 27, 2026" title="A courtyard can change how a family gathers" /></div></section>

    <footer className="nh-footer" id="contact"><div className="nh-shell"><div className="nh-footer-lead co-flex co-items-end co-justify-between"><h2>Architecture for<br />a considered life.</h2><a className="co-inline-flex co-items-center" href="mailto:studio@noirhabitat.example">studio@noirhabitat.example <ThemeIcon name="arrow-to-top-right" size={18} /></a></div><div className="nh-footer-grid co-grid"><a className="nh-brand co-inline-flex co-items-center" href="#top"><b>N/H</b><span>Noir Habitat<small>Architecture &amp; interiors</small></span></a><div><b>Studio</b><a href="#studio">About</a><a href="#services">Services</a><a href="#work">Projects</a></div><div><b>Contact</b><a href="mailto:studio@noirhabitat.example">Email studio</a><span>Jakarta · Indonesia</span><span>+62 21 555 0184</span></div><div><b>Elsewhere</b><a href="#contact">Instagram</a><a href="#contact">LinkedIn</a><a href="#contact">ArchDaily</a></div></div><div className="nh-footer-bottom co-flex co-items-center co-justify-between"><span>© 2026 Coordiation. All rights reserved.</span><a className="co-inline-flex co-items-center" href="#top">Back to top <ThemeIcon name="arrow-to-top-right" size={13} /></a></div></div></footer>
  </main>;
}
