import type { Metadata } from "next";
import Link from "@/app/_components/SiteLink";
import MobileNav from "../../_components/MobileNav";
import SolarIcon from "../../_components/SolarIcon";
import registry from "../../docs/generated/theme-registry.json";
import ThemeCommand from "../ThemeCommand";

export const metadata: Metadata = { title: "Quiet Journal theme — Coordiation CSS", description: "Preview and install the Quiet Journal open-code application theme.", openGraph: { title: "Quiet Journal — Coordiation Themes", description: "A warm illustrated personal journal built with Coordiation.", images: ["/themes/quiet-journal/hero-desk.webp"] }, twitter: { card: "summary_large_image", title: "Quiet Journal — Coordiation Themes", description: "A warm illustrated personal journal built with Coordiation.", images: ["/themes/quiet-journal/hero-desk.webp"] } };

export default function QuietJournalThemePage() {
  const theme = registry.themes.find((item) => item.name === "quiet-journal")!;
  return <main className="theme-detail-page"><header className="site-header"><Link className="brand" href="/" aria-label="Coordiation CSS home"><img src="/coordiation-logo.png" alt="" /><span>Coordiation</span><span className="brand-product">Themes</span></Link><nav aria-label="Main navigation"><Link href="/themes">All themes</Link><Link href="/components">Components</Link><Link href="/icons">Icons</Link><Link href="/docs/themes">Docs</Link></nav><MobileNav /><Link className="header-cta" href={theme.preview}>Full preview <SolarIcon name="arrow-to-top-right" size={15} /></Link></header>
    <section className="theme-detail-hero quiet-journal-detail"><div><p className="component-overline">THEME 002 · {theme.status.toUpperCase()}</p><h1>{theme.title}</h1><p>{theme.description} Inspired by the warmth of independent journals and rebuilt as an original, responsive Coordiation application.</p><div className="theme-tags">{theme.categories.map((category)=><span key={category}>{category}</span>)}</div></div><div><ThemeCommand command={theme.command} /><small>The Coordiation CLI installs the page, stylesheet, icon component, required Solar SVG files, and six optimized original illustrations.</small></div></section>
    <section className="theme-preview-frame"><div className="theme-browser-bar"><span><i/><i/><i/></span><code>/quiet-journal</code><Link href={theme.preview}>Open full screen <SolarIcon name="arrow-to-top-right" size={14}/></Link></div><iframe src={theme.preview} title="Quiet Journal live theme preview" loading="eager" /></section>
    <section className="theme-detail-spec"><div><p className="component-overline">STRUCTURE</p><h2>{theme.sections.length} thoughtful sections</h2><p>Every section is named in the registry so a person or AI agent can safely customize the journal without guessing from the rendered page.</p></div><ol>{theme.sections.map((section,index)=><li key={section}><span>{String(index+1).padStart(2,"0")}</span><b>{section}</b></li>)}</ol></section>
    <section className="theme-detail-files"><div><p className="component-overline">COORDIATION-NATIVE</p><h2>Framework source.<br />Original illustration.</h2></div><div><h3>Installed files</h3>{theme.files.map(file=><code key={file.target}>{file.target}</code>)}<h3>Public assets</h3>{theme.assets.map(asset=><code key={asset}>{asset}</code>)}</div><aside><SolarIcon name="code" size={26}/><p>The page uses {theme.coordiationUtilityCount} verified <code>co-*</code> utilities, a bundled <code>ThemeIcon</code> component, and the <code>{theme.namespace}</code> design namespace.</p><a href={theme.installPath}>Inspect registry item <SolarIcon name="arrow-to-top-right" size={14} /></a></aside></section>
    <section className="theme-detail-cta"><p className="component-overline">READY TO WRITE</p><h2>Make the journal yours.</h2><p>Replace the author, essays, email address, and illustrations while preserving semantic content, accessible controls, and Coordiation copyright.</p><ThemeCommand command={theme.command} /></section>
  </main>;
}
